---
name: Release package

on:
  release:
    types: [released]

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/setup/poetry
        with:
          os: ${{ job.os }}
          python-version: '3.11'
          poetry-install-options: "--only=main"
          poetry-export-options: "--only=main"

      - name: Publish package to PyPI
        run: poetry publish --build -u __token__ -p ${{ secrets.PYPI_PASSWORD }}
...
